language: cpp

.bionic-job-template: &bionic-job
  os: linux
  dist: bionic
  install:
  - sudo apt update
  - sudo apt install --yes
    $COMPILER_PACKAGE
    libboost-program-options$BOOST_VERSION-dev
    libboost-test$BOOST_VERSION-dev
  script:
  - mkdir Build
  - cd Build
  - cmake .. -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DCMAKE_CXX_COMPILER=$COMPILER_NAME
  - cmake --build . --target check

.coverage-job-template: &coverage-job
  os: linux
  dist: bionic
  install:
  - sudo apt update
  - sudo apt install --yes gcovr libboost-program-options-dev libboost-test-dev
  script:
  - mkdir Build
  - cd Build
  - cmake .. -DCMAKE_BUILD_TYPE=Debug -DBURST_ENABLE_COVERAGE=YES
  - cmake --build . --target coverage

matrix:
  include:
  - <<: *bionic-job
    env: COMPILER_PACKAGE=clang-3.9 COMPILER_NAME=clang++-3.9 BOOST_VERSION=1.62 BUILD_TYPE=Debug
  - <<: *bionic-job
    env: COMPILER_PACKAGE=clang-3.9 COMPILER_NAME=clang++-3.9 BOOST_VERSION=1.62 BUILD_TYPE=Release
  - <<: *bionic-job
    env: COMPILER_PACKAGE=clang-3.9 COMPILER_NAME=clang++-3.9 BOOST_VERSION=1.65 BUILD_TYPE=Debug
  - <<: *bionic-job
    env: COMPILER_PACKAGE=clang-3.9 COMPILER_NAME=clang++-3.9 BOOST_VERSION=1.65 BUILD_TYPE=Release
  - <<: *bionic-job
    env: COMPILER_PACKAGE=clang-4.0 COMPILER_NAME=clang++-4.0 BOOST_VERSION=1.62 BUILD_TYPE=Debug
  - <<: *bionic-job
    env: COMPILER_PACKAGE=clang-4.0 COMPILER_NAME=clang++-4.0 BOOST_VERSION=1.62 BUILD_TYPE=Release
  - <<: *bionic-job
    env: COMPILER_PACKAGE=clang-4.0 COMPILER_NAME=clang++-4.0 BOOST_VERSION=1.65 BUILD_TYPE=Debug
  - <<: *bionic-job
    env: COMPILER_PACKAGE=clang-4.0 COMPILER_NAME=clang++-4.0 BOOST_VERSION=1.65 BUILD_TYPE=Release
  - <<: *bionic-job
    env: COMPILER_PACKAGE=clang-5.0 COMPILER_NAME=clang++-5.0 BOOST_VERSION=1.62 BUILD_TYPE=Debug
  - <<: *bionic-job
    env: COMPILER_PACKAGE=clang-5.0 COMPILER_NAME=clang++-5.0 BOOST_VERSION=1.62 BUILD_TYPE=Release
  - <<: *bionic-job
    env: COMPILER_PACKAGE=clang-5.0 COMPILER_NAME=clang++-5.0 BOOST_VERSION=1.65 BUILD_TYPE=Debug
  - <<: *bionic-job
    env: COMPILER_PACKAGE=clang-5.0 COMPILER_NAME=clang++-5.0 BOOST_VERSION=1.65 BUILD_TYPE=Release
  - <<: *bionic-job
    env: COMPILER_PACKAGE=clang-6.0 COMPILER_NAME=clang++-6.0 BOOST_VERSION=1.62 BUILD_TYPE=Debug
  - <<: *bionic-job
    env: COMPILER_PACKAGE=clang-6.0 COMPILER_NAME=clang++-6.0 BOOST_VERSION=1.62 BUILD_TYPE=Release
  - <<: *bionic-job
    env: COMPILER_PACKAGE=clang-6.0 COMPILER_NAME=clang++-6.0 BOOST_VERSION=1.65 BUILD_TYPE=Debug
  - <<: *bionic-job
    env: COMPILER_PACKAGE=clang-6.0 COMPILER_NAME=clang++-6.0 BOOST_VERSION=1.65 BUILD_TYPE=Release
  - <<: *bionic-job
    env: COMPILER_PACKAGE=g++-6 COMPILER_NAME=g++-6 BOOST_VERSION=1.62 BUILD_TYPE=Debug
  - <<: *bionic-job
    env: COMPILER_PACKAGE=g++-6 COMPILER_NAME=g++-6 BOOST_VERSION=1.62 BUILD_TYPE=Release
  - <<: *bionic-job
    env: COMPILER_PACKAGE=g++-6 COMPILER_NAME=g++-6 BOOST_VERSION=1.65 BUILD_TYPE=Debug
  - <<: *bionic-job
    env: COMPILER_PACKAGE=g++-6 COMPILER_NAME=g++-6 BOOST_VERSION=1.65 BUILD_TYPE=Release
  - <<: *bionic-job
    env: COMPILER_PACKAGE=g++-7 COMPILER_NAME=g++-7 BOOST_VERSION=1.62 BUILD_TYPE=Debug
  - <<: *bionic-job
    env: COMPILER_PACKAGE=g++-7 COMPILER_NAME=g++-7 BOOST_VERSION=1.62 BUILD_TYPE=Release
  - <<: *bionic-job
    env: COMPILER_PACKAGE=g++-7 COMPILER_NAME=g++-7 BOOST_VERSION=1.65 BUILD_TYPE=Debug
  - <<: *bionic-job
    env: COMPILER_PACKAGE=g++-7 COMPILER_NAME=g++-7 BOOST_VERSION=1.65 BUILD_TYPE=Release
  - <<: *bionic-job
    env: COMPILER_PACKAGE=g++-8 COMPILER_NAME=g++-8 BOOST_VERSION=1.62 BUILD_TYPE=Debug
  - <<: *bionic-job
    env: COMPILER_PACKAGE=g++-8 COMPILER_NAME=g++-8 BOOST_VERSION=1.62 BUILD_TYPE=Release
  - <<: *bionic-job
    env: COMPILER_PACKAGE=g++-8 COMPILER_NAME=g++-8 BOOST_VERSION=1.65 BUILD_TYPE=Debug
  - <<: *bionic-job
    env: COMPILER_PACKAGE=g++-8 COMPILER_NAME=g++-8 BOOST_VERSION=1.65 BUILD_TYPE=Release
  - <<: *coverage-job
