#ifndef BURST__ALGORITHM__COUNTING_SORT__COUNTING_SORT_MOVE_HPP
#define BURST__ALGORITHM__COUNTING_SORT__COUNTING_SORT_MOVE_HPP

#include <burst/algorithm/counting_sort/counting_sort_move_par.hpp>
#include <burst/algorithm/counting_sort/counting_sort_move_seq.hpp>

#endif // BURST__ALGORITHM__COUNTING_SORT__COUNTING_SORT_MOVE_HPP
