#ifndef BURST__ALGORITHM__COUNTING_SORT__COUNTING_SORT_COPY_HPP
#define BURST__ALGORITHM__COUNTING_SORT__COUNTING_SORT_COPY_HPP

#include <burst/algorithm/counting_sort/counting_sort_copy_par.hpp>
#include <burst/algorithm/counting_sort/counting_sort_copy_seq.hpp>

#endif // BURST__ALGORITHM__COUNTING_SORT__COUNTING_SORT_COPY_HPP
