name: macOS

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-10.15]
        build_type: ["Debug", "Release"]

    runs-on: ${{matrix.os}}
    steps:
    - uses: actions/checkout@v2

    - name: Install Homebrew dependencies
      run: |
        brew install cmake
        brew install boost
        brew install doctest

    - name: Configure
      run: |
        cmake -S . -B Build/burst -DCMAKE_BUILD_TYPE=${{matrix.build_type}}

    - name: Build and test
      run: |
        cmake --build Build/burst --target check
