name: macOS

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-10.15]
        build_type: ["Debug", "Release"]

    runs-on: ${{matrix.os}}
    steps:
    - uses: actions/checkout@v2

    - name: Install Homebrew dependencies
      run: |
        brew install cmake
        brew install boost

    - name: Install doctest
      run: |
        git clone https://github.com/onqtam/doctest.git third_party/doctest
        git -C third_party/doctest checkout 2.3.3
        cmake -S third_party/doctest -B Build/third_party/doctest -DCMAKE_BUILD_TYPE=Release
        sudo cmake --build Build/third_party/doctest --target install/fast

    - name: Configure
      run: |
        cmake -S . -B Build/burst -DCMAKE_BUILD_TYPE=${{matrix.build_type}}

    - name: Build and test
      run: |
        cmake --build Build/burst --target check
